### ISSUE TITLE
No DTMF Tones

### ISSUE THREAD

**Issue by leachmurray** [collecttix/ctxSip#6] opened 2016-06-09 10:53 UTC
Awesome work here, I wonder if there is a plan to implement DTMF tones via RFC 2833, there seems to be an mp3 relating to but does not function for me

**Comment by bmac901** [comment] 2016-06-09 17:05
The dtmf tone is actually just a sip packet, the mp3 is just a tone to provide user feedback.  Can you put up a Gist of the sip logs?  What kind of server is it connecting to?

**Comment by leachmurray** [comment] 2016-06-09 19:25
Heres my error from console log in Chrome, this comes ONLY when I press '0'

sip.min.js:1 
Uncaught TypeError: Invalid tones: 0
r.dtmf @ sip.min.js:1
ctxSip.sipSendDTMF @ app.js:1
(anonymous function) @ app.js:1
m.event.dispatch @ jquery-1.11.1.min.js:1
r.handle @ jquery-1.11.1.min.js:1

**Comment by leachmurray** [comment] 2016-06-09 19:25
I am using the fork to Kazoo-ui connecting to my own custer of Kazoo

**Comment by bmac901** [comment] 2016-06-09 22:09
I was able to reproduce the problem in Kazoo-UI, but not my in my code.  I bet it was an upsteam bug in sip.js that has since been fixed. @Bat-o-matic is the one who originally merged it into Kazoo-UI.  You can ask him to update Kazoo-UI with the newest ctxSip or open a ticket with 2600hz.

I'll be glad to help them anyway I can.

Thanks for the bug report.

**Closed by bmac901** 2016-06-09 22:09 UTC

**Comment by leachmurray** [comment] 2016-06-12 22:29
noob alert, I wish I knew how to contact him
